### PR TITLE
feat(openid): add openid connect config for oauth

### PR DESCRIPTION
**Pull request by seanmonstar**
Should be merged along with https://github.com/mozilla/fxa-oauth-server/pull/368

### CODE REVIEW

**Comment by rfk** [comment]
@jrgm to r?

It's probably not a big deal for a dev environment, but maybe we should consider generating a fresh secret a build time rather than committing a fixed secret to github?  The auth-server role does this at https://github.com/mozilla/fxa-dev/blob/master/roles/auth/handlers/main.yml#L8

**Comment by jrgm** [comment]
LGTM, modulo @rfk's point on dynamically generating the key.

**Comment by seanmonstar** [comment]
For dev purposes, security is a non-issue. Adding the ability to generate keys automatically to the fxa-oauth-server repo seems to have little value to me...

**Comment by jrgm** [comment]
@seanmonstar - sure, seems good to me.

**Comment by rfk** [comment]
Merging this in the interests of moving forward with the OIDC stuff, but I filed https://github.com/mozilla/fxa-dev/issues/212 to revisit the issue of generating it at stack build time, as having even dev secrets sitting around in github just gives me the willies...

**Pull request merged**
