### PR TITLE
feat(deploy): add a box that works with a local content server

### LINKED ISSUE #213: Deploy a box that works with a local content server
This is probably going to involve a lot of config changes.

For circle-ci we currently use a custom fxa-local-dev box to run functional tests.
We need to get rid of it because that box is a quick hack.

Ref http://fxadeploybox.dev.lcip.org:9000/

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #213

### CODE REVIEW

**Comment by vladikoff** [comment]
@jrgm please r?

Surprisingly enough setting one option allows a local 127.0.0.1 content server to talk to all remote servers. 

I will create a new PR in the content server to allow new contributors to just use this remote box to test their local patches:

````
{
  "csp": {
    "enabled": false
  },
  "public_url": "http://127.0.0.1:3030",
  "fxaccount_url": "https://content.dev.lcip.org/auth",
  "oauth_client_id": "ea3ca969f8c6bb0d",
  "oauth_url": "https://oauth-content.dev.lcip.org",
  "profile_url": "https://content.dev.lcip.org/profile",
  "profile_images_url": "https://content.dev.lcip.org/profile",
  "allowed_parent_origins": ["https://123done-content.dev.lcip.org/"],
  "use_https": false
}
``` 

![image](https://cloud.githubusercontent.com/assets/128755/17003962/76461a48-4ea0-11e6-9751-7f3eddd72d81.png)

**Comment by vladikoff** [comment]
@jrgm will this auto update like latest?

**Comment by vladikoff** [comment]
Add node 4 https://github.com/mozilla/fxa-dev/blob/master/aws/environments/latest4.yml#L14

**Comment by jrgm** [comment]
LGTM. It will auto update every 10 minutes. As mentioned aws/environments/latest4.yml shows using node 4.

**Pull request merged**
