### PR TITLE
[DO NOT MERGE] convert fxa-dev to use docker images

### PR DESCRIPTION
**Pull request by jrgm**
Just making this a PR for tracking purposes (and of course review comments). See https://github.com/mozilla/fxa-dev/pull/300#issuecomment-289257733 for previous comments.

### CODE REVIEW

**Comment by jrgm** [comment]
Also teamcity tests pass (modulo 3 on marionette tests):
https://tc-test.dev.lcip.org/viewLog.html?buildId=9177&tab=buildResultsDiv&buildTypeId=fxa_FxadevServerTests
https://tc-test.dev.lcip.org/viewLog.html?buildId=9180&tab=buildResultsDiv&buildTypeId=fxa_FxadevTests

**Comment by vladikoff** [comment]
@jrgm I get `TASK [Waiting for instance to join ELB (ignore FAILED RETRYING log messages)] **
FAILED - RETRYING: TASK: Waiting for instance to join ELB (ignore FAILED RETRYING log messages) (40 retries left).
FAILED - RETRYING: TASK: Waiting for instance to join ELB (ignore FAILED RETRYING log messages) (39 retries left).`

....

**Comment by vladikoff** [comment]
image

**Comment by jrgm** [comment]
> @jrgm I get
> 
> TASK [Waiting for instance to join ELB (ignore FAILED RETRYING log messages)] **
> FAILED - RETRYING: TASK: Waiting for instance to join ELB (ignore FAILED RETRYING log messages) (40 retries left).

I didn't say it was pretty ;-). Hint: ignore FAILED RETRYING log messages.

(Seriously, unless I find something else, if you want to poll, ansible will squawk like this.).

I could poll less often, or literally sleep for an initial period of time.

**Comment by vladikoff** [comment]
This is ready but will remain as its own branch!

**Pull request closed without merging**
