### PR TITLE
fixes for running with ansible 2.8

### LINKED ISSUE #455: Unable to create stacks, cloudinit error installing python2-dnf
> cloud-init-output.log:10:34:08 fatal: [localhost]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "msg": "[Errno 2] No such file or directory", "rc": 2}

cc @jrgm

### PR DESCRIPTION
**Pull request by jrgm**
1. fixes #455 - where we use yum, tell it to `use_backend: yum` and not dnf
2. `docker_container` is now strict about quoting environment arguments (sometimes)
3. now that we have an elastic IP, point the `meta-` address to that EIP

r? - @jbuck, @shane-tomlinson

### CODE REVIEW

**Comment by jrgm** [comment]
Sorry, forgot to mention. This change will probably break fxa-dev instances that are still running ansible <2.8, so probably should not merge this right away, and check with folks on Monday. (On the other hand, deploying a new box can't be done on the current head of the docker branch).

**Comment by shane-tomlinson** [comment]
@jrgm - When trying to create a new box, I still see this in cloud-init-output.log:

> 10:48:32 failed: [localhost] (item=[u'docker', u'gcc-c++', u'git', u'ntp', u'python-dnf']) => {"ansible_loop_var": "item", "changed": false, "item": ["docker", "gcc-c++", "git", "ntp", "python-dnf"], "msg": "No package matching 'python-dnf' found available, installed or updated", "rc": 126, "results": ["docker-18.06.1ce-8.28.amzn1.x86_64 providing docker is already installed", "gcc-c++-4.8.5-1.22.amzn1.noarch providing gcc-c++ is already installed", "git-2.14.5-1.60.amzn1.x86_64 providing git is already installed", "ntp-4.2.8p12-1.39.amzn1.x86_64 providing ntp is already installed", "No package matching 'python-dnf' found available, installed or updated"]}
10:48:32

**Comment by jrgm** [comment]
set `fxadev_git_version: docker-ansible-2.8` in aws/environments/stomlinson.yml

**Comment by jrgm** [comment]
Actually, more explicitly:
1) git checkout docker-ansible-2.8
2) git checkout -b docker-ansible-2.8-shane
3) echo 'fxadev_git_version: docker-ansible-2.8-shane' >> aws/environments/stomlinson.yml
4) git add aws/environments/stomlinson.yml; git commit -m myhack; git push origin docker-ansible-2.8-shane
5) make stomlinson
6) GOOAAAALLLL!!!

**Comment by shane-tomlinson** [comment]
> GOOAAAALLLL!!!

Works perfectly, thank you @jrgm!

**Comment by jrgm** [comment]
So can I just merge this? I can fixup latest, stable, and fxaci, but other instances will likely break. Comments?

**Comment by jbuck** [comment]
+1 for merging/deploying it

**Comment by shane-tomlinson** [comment]
Merge and fix!

**Review by shane-tomlinson — APPROVED** [review]
r+, merge and fix @jrgm, thank you very much for this!

**Comment by shane-tomlinson** [comment]
Note, Softvision is testing Trailhead changes against latest, so when we break it we'll want it back pretty quickly.

**Comment by jrgm** [comment]
It's now late evening for Softvision, I think, so merging now. Will redeploy `latest` immediately; `stable` will not run cron till tomorrow.

**Comment by jrgm** [comment]
`Latest` is back and running tests; was down for about 15 minutes (teardown and freshbuild).

Note: for other fxadev instances, you can run `sudo pip install --install-option='--install-scripts=/usr/bin' -U ansible`, and that will get rid of the incompatible ansible syntax change (`use_backend` new in 2.7+). Note 2: the `--install-option='--install-scripts=/usr/bin'` part must be used in that pip command.

**Comment by jrgm** [comment]
`stable`.dev.lcip.org has been updated, retaining previous data in RDS. 

`fxaci`.dev.lcip.org was fixed with the above `pip` command. 

Done.

**Pull request merged**
