### PR TITLE
chore(notifications): Remove the defunct fxa-notification-server

### PR DESCRIPTION
**Pull request by rfk**
A companion to https://github.com/mozilla/fxa-auth-db-mysql/pull/177, this removes the never-used and almost-certainly-never-going-to-be-used "notification server" from our dev stack.

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
In `aws/cloudformation/moz-single.json`, there is a reference to [FxaNotificationsRedisCluster](https://github.com/mozilla/fxa-dev/blob/bd09d92275e1d991be29489ce9e31e1ca916fb4a/aws/cloudformation/moz-single.json#L438) and an [Fxa Notifications Elasticache Group](https://github.com/mozilla/fxa-dev/blob/bd09d92275e1d991be29489ce9e31e1ca916fb4a/aws/cloudformation/moz-single.json#L428). Do these need to be removed?

If this merges before the auth-db-mysql PR, will there be any problems?

**Comment by rfk** [comment]
> If this merges before the auth-db-mysql PR, will there be any problems?

I don't think so, it should just stop using those parts of the code.

**Comment by rfk** [comment]
Thanks @shane-tomlinson, updated to remove those left-over references.

**Comment by rfk** [comment]
And I've also confirmed that I can build a fresh stack using this configuration.  Ready for another r?

**Pull request merged**
