### PR TITLE
add oauth-internal server

### PR DESCRIPTION
**Pull request by seanmonstar**
DON'T MERGE. I have no idea what I'm doing. I feel there should be a little more to mount the servers on their respective paths, but I started flipping tables.

### CODE REVIEW

**Comment by seanmonstar** [comment]
I actually could really use help here. Who can help? @dannycoates? @vladikoff?

**Comment by dannycoates** [comment]
@seanmonstar I can look at it this afternoon

**Comment by dannycoates** [comment]
Ok, at first glance it looks like now's a good time to move all the oauth processes: server, internal, console, to the same role. What's the priority on this? I'm pretty busy this week.

**Comment by vladikoff** [comment]
We have the stable console working at https://oauth-stable.dev.lcip.org/console/clients so unless stable gets updated we should be okay for a few days

**Comment by jrgm** [comment]
I'm due to update stable tomorrow ;-)

**Comment by seanmonstar** [comment]
Stable won't be updated to include this, though. Stable matches prod, and this isn't going to prod yet.

**Comment by vladikoff** [comment]
stable is another dev env, **stage** is matching prod.

**Comment by ckarlof** [comment]
In general, the code in stable matches the code on prod. However, it raises the question what version of the console runs on stable, since the console isn't in prod. :)

**Comment by jrgm** [comment]
So, we're not putting a new oauth version into production tomorrow so oauth in stable will stay the same, and that means oauth-console should stay fine (just updating auth, auth-db, content). 

Anyways, I can work on the oauth/oauth-console config tomorrow, unless someone gets there first.

**Comment by vladikoff** [comment]
@jrgm we should discuss it in the meeting tomorrow morning if possible.

**Comment by jrgm** [comment]
@vladikoff sure

**Comment by vladikoff** [comment]
@seanmonstar can we just patch the oauth-server to include `if (config.get('env') !== 'prod') {` like it used to. So the client endpoints are open in dev? I feel like patching fxa-dev might be really complex 

See https://github.com/mozilla/fxa-oauth-server/commit/07a61af2141e7fffc54d08a16acac48073103570#diff-7bd084e1642aa17e0074c18f5a25a0aeR62

cc @jrgm

**Pull request merged**
