### PR TITLE
chore(config): move mailer config into auth

### PR DESCRIPTION
**Pull request by vladikoff**
@jrgm r?

### CODE REVIEW

**Comment by vladikoff** [comment]
```
******
fatal: [ec2-54-191-238-43.us-west-2.compute.amazonaws.com]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'auth_mailer_git_repo' is undefined\n\nThe error appears to have been in '/Users/vladikoff/mozilla/fxa-dev/roles/email/tasks/main.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: install fxa-auth-mailer\n  ^ here\n"}
```

got this, need to fix up

**Comment by vladikoff** [comment]
@jrgm the deploy works but I get: 

```
36,"host":"127.0.0.1"}}
{"Timestamp":1488909593357000000,"Logger":"fxa-auth-mailer","Type":"db.db","Severity":4,"Pid":29360,"EnvVersion":"2.0","Fields":{"message":"Failed to connect to database, retrying..."}}
{"Timestamp":1488909603364000000,"Logger":"fxa-auth-mailer","Type":"db.db","Severity":4,"Pid":29360,"EnvVersion":"2.0","Fields":{"message":"Failed to connect to database, retrying..."}}
{"Timestamp":1488909613366000000,"Logger":"fxa-auth-mailer","Type":"db.db","Severity":4,"Pid":29360,"EnvVersion":"2.0","Fields":{"message":"Failed to connect to database, retrying..."}}
{"Timestamp":1488909623367000000,"Logger":"fxa-auth-mailer","Type":"db.db","Severity":4,"Pid":29360,"EnvVersion":"2.0","Fields":{"message":"Failed to connect to database, retrying..."}}
{"Timestamp":1488909633368000000,"Logger":"fxa-auth-mailer","Type":"db.db","Severity":4,"Pid":29360,"EnvVersion":"2.0","Fields":{"message":"Failed to connect to database, retrying..."}}
{"Timestamp":1488909643370000000,"Logger":"fxa-auth-mailer","Type":"db.db","Severity":4,"Pid":29360,"EnvVersion":"2.0","Fields":{"message":"Failed to connect to database, retrying..."}}
{"Timestamp":1488909653372000000,"Logger":"fxa-auth-mailer","Type":"db.db","Severity":4,"Pid":29360,"EnvVersion":"2.0","Fields":{"message":"Failed to connect to database, retrying..."}}
```

**Comment by vladikoff** [comment]
Oh nevermind it actually connects, just takes a bit of ti,e

**Comment by jrgm** [comment]
In general this looks good. Is this running somewhere?

**Comment by vladikoff** [comment]
> In general this looks good. Is this running somewhere?

https://newmailerconfig.dev.lcip.org

**Comment by jrgm** [comment]
Hmm. I got 
`TASK [ses : install postfix main.cf] *******************************************
fatal: [ec2-54-202-54-172.us-west-2.compute.amazonaws.com]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /etc/postfix does not exist"}
  to retry, use: --limit @/Users/jrgm/github/mozilla/fxa-dev/aws/dev.retry` 
when I ran this.

**Comment by vladikoff** [comment]
> Hmm. I got
TASK [ses : install postfix main.cf] ******************************************* fatal: [ec2-54-202-54-172.us-west-2.compute.amazonaws.com]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /etc/postfix does not exist"} to retry, use: --limit @/Users/jrgm/github/mozilla/fxa-dev/aws/dev.retry
when I ran this.

Eh I guess this is one of those things that only happens on new boxes probably

**Comment by jrgm** [comment]
So, with https://github.com/mozilla/fxa-dev/pull/297 merged, we can close this one, right?

**Comment by vladikoff** [comment]
Closing! Thanks @jrgm !

**Pull request closed without merging**
